spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.arpit: DEBUG
    org.springframework.boot: INFO
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
    org.hibernate.SQL: DEBUG
